public class EmailProccesHandler{
 /*   @InvocableMethod
public static void emailInProccesBuilder(List<Contact> lsttContact){
        System.debug(lsttContact);
     List<String> sentTo = new List<String>();
        for(Contact con : lsttContact){
            sentTo.add(con.Email);
        }
        Messaging.SingleEmailMessage msg= new Messaging.SingleEmailMessage();
        msg.setToAddresses(sentTo);
        msg.subject='Your Contact is Succesfully Created';
        msg.plaintextbody='Hello Your Contact is created';
        Messaging.SingleEmailMessage[] msgs = new List<Messaging.SingleEmailMessage>{msg};
            Messaging.SendEmailResult[] results= Messaging.sendEmail(msgs);
        	
    }*/

}